name: Build and Deploy WordPress

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -d my-wordpress-image .
      #run: docker build . --file Dockerfile --tag my-image-name:latest
    - name: run & test Container
      run: docker run -itd --name hello-world -p 8080:8080   my-wordpress-image:latest
    - run: sleep 75 && curl localhost:8080
    - name: Push Docker image to a container registry
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker tag my-wordpress-image your-docker-username/wordpress:latest
        docker push your-docker-username/wordpress:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy WordPress
      run: |
        docker-compose up -d
      env:
        WORDPRESS_DB_PASSWORD: ${{ secrets.WP_DB_PASSWORD }}
