name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest
    - name: run & test Container
      run: docker run -itd --name war-lidor -p 80:8080 my-image-name:latest
    - run: sleep 90 && curl localhost:8080
